spring:
  # 数据源配置
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    # MYSQL 5 驱动：com.mysql.jdbc.Driver，MYSQL 6+ 驱动：com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8
    filters: stat
    username: root
    password: 123456
    # 连接池配置
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 1
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存时间
    minEvictableIdleTimeMillis: 300000
    validationWuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开 PSCache，并且指定每个连接上 PSCache 的大小
    poolPreparedStatements: true
    maxOpenPreparedStatement: 20
  transaction:
    rollback-on-commit-failure: true

mybatis:
  mapper-locations: classpath:mapping/user.mapper.xml
  config-location: classpath:mybatis/mybatis.cfg.xml

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguements: true
  params: count=countSql